sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version
    - sudo apt-get install ghostscript -y
    - sudo apt-get install imagemagick -y
    - sudo apt-get install p7zip-full -y
    - 7z x ./data/web_log.tsv.7z -o./data/

script:
  - bash ./task/task1.sh --file=./images/ -p "test1"
  - ls -l ./images/
  - bash ./task/task1.sh -f ./images/0657cda644f08b4.jpg -q 50 -s "test2"
  - ls -l ./images/
  - bash ./task/task1.sh -f ./images/Octicons-cloud-download.svg -c -p "test3"
  - ls -l ./images/
  - bash ./task/task1.sh -f ./images/ -r 50 -s "test4"
  - ls -l ./images/
  - bash ./task/task1.sh -f ./images/ -m "DcmTruman" -p "test5"
  - ls -l ./images/
  - bash ./task/task2.sh
  - bash ./task/task3.sh
  - bash ./task/task3.sh /images/ksclogo-medium.gif

after_script:
  - /usr/bin/shellcheck ./task/task1.sh
  - /usr/bin/shellcheck ./task/task2.sh
  - /usr/bin/shellcheck ./task/task3.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
